package com.ecoverse.security;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Short-lived one-time authorization code store for OAuth2 token delivery.
 *
 * After Google OAuth2 succeeds, we generate a random code, store the JWT tokens
 * associated with it, and redirect to the frontend with ONLY the code in the URL.
 * The frontend then exchanges this code for the actual tokens via a POST request.
 *
 * This prevents tokens from appearing in:
 * - Browser history
 * - Server access logs
 * - Referer headers
 * - Proxy logs
 *
 * Codes expire after 30 seconds and are single-use (deleted after exchange).
 * Expired codes are cleaned up every 60 seconds by a scheduled task.
 */
@Component
public class OAuth2AuthorizationCodeService {

    private static final Logger logger = LoggerFactory.getLogger(OAuth2AuthorizationCodeService.class);

    private static final int CODE_EXPIRY_SECONDS = 30;

    private final Map<String, PendingAuth> codeStore = new ConcurrentHashMap<>();

    /**
     * Store tokens against a one-time authorization code.
     *
     * @param code        the one-time code (generated by OAuth2SuccessHandler)
     * @param accessToken JWT access token
     * @param refreshToken JWT refresh token
     * @param userId      the authenticated user's ID
     */
    public void store(String code, String accessToken, String refreshToken, Long userId) {
        codeStore.put(code, new PendingAuth(accessToken, refreshToken, userId,
                LocalDateTime.now().plusSeconds(CODE_EXPIRY_SECONDS)));
    }

    /**
     * Exchange a one-time code for tokens. The code is consumed (deleted) on first use.
     *
     * @param code the one-time code from the OAuth redirect
     * @return PendingAuth with tokens, or null if code is invalid/expired/already-used
     */
    public PendingAuth exchange(String code) {
        PendingAuth pending = codeStore.remove(code); // Single-use: remove on read
        if (pending == null) {
            return null;
        }
        if (pending.expiresAt.isBefore(LocalDateTime.now())) {
            return null; // Expired
        }
        return pending;
    }

    /**
     * Clean up expired codes periodically.
     * Runs every 60 seconds via Spring's @Scheduled annotation.
     * This prevents memory leaks from expired codes that are never exchanged.
     */
    @Scheduled(fixedRate = 60000)
    public void cleanupExpired() {
        LocalDateTime now = LocalDateTime.now();
        int sizeBefore = codeStore.size();
        codeStore.entrySet().removeIf(entry -> entry.getValue().expiresAt.isBefore(now));
        int removed = sizeBefore - codeStore.size();
        if (removed > 0) {
            logger.debug("Cleaned up {} expired OAuth2 authorization codes", removed);
        }
    }

    public static class PendingAuth {
        public final String accessToken;
        public final String refreshToken;
        public final Long userId;
        public final LocalDateTime expiresAt;

        public PendingAuth(String accessToken, String refreshToken, Long userId, LocalDateTime expiresAt) {
            this.accessToken = accessToken;
            this.refreshToken = refreshToken;
            this.userId = userId;
            this.expiresAt = expiresAt;
        }
    }
}
